import {
  pgTable,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  index,
} from "drizzle-orm/pg-core";

export const knowledgeEntries = pgTable(
  "knowledge_entries",
  {
    id: uuid("id")
      .defaultRandom()
      .primaryKey(),

    userId: text("user_id").notNull(),

    title: text("title").notNull(),

    content: text("content").notNull().default(""),

    summary: text("summary"),

    category: text("category")
      .notNull()
      .default("reference"),

    sourceType: text("source_type")
      .notNull()
      .default("manual"),

    sourceId: text("source_id"),

    sourceName: text("source_name"),

    sourceTaskId: uuid("source_task_id"),

    tags: text("tags"),

    embedding: text("embedding"),

    viewCount: integer("view_count").notNull().default(0),

    isArchived: boolean("is_archived").notNull().default(false),
    isPinned: boolean("is_pinned").notNull().default(false),

    isAutoGenerated: boolean("is_auto_generated").notNull().default(false),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    userCategoryIdx: index("ke_user_category_idx").on(
      table.userId,
      table.category,
      table.createdAt
    ),

    sourceIdx: index("ke_source_idx").on(table.sourceType, table.sourceId),

    archiveIdx: index("ke_archive_idx").on(table.userId, table.isArchived),
  })
);

export type KnowledgeEntry = typeof knowledgeEntries.$inferSelect;
export type NewKnowledgeEntry = typeof knowledgeEntries.$inferInsert;

export const CATEGORY_LABELS: Record<string, string> = {
  insight: "洞察",
  method: "方法",
  template: "模板",
  reference: "参考",
  decision: "决策",
  archive: "归档",
} as const;

export const SOURCE_TYPE_LABELS: Record<string, string> = {
  task: "任务沉淀",
  retrospective: "复盘洞察",
  sop: "方法论",
  manual: "手动创建",
  import: "外部导入",
  feishu: "飞书文档",
} as const;
