// 知识沉淀引擎
// 自动将任务完成、复盘记录转化为结构化知识条目

import { db } from "@/db";
import { knowledgeEntries } from "@/db/schema";
import { callDeepSeek } from "@/lib/ai/deepseek";
import { reindexEntry, backfillMissingEmbeddings, countMissingEmbeddings } from "@/lib/rag/maintenance";

/**
 * 从任务完成中沉淀知识
 *
 * 当任务状态变为 "done" 时调用，自动提取：
 * 1. 关键洞察（标题 + 总结）
 * 2. 方法/SOP（如果用户填写了完成反思）
 * 3. 标签（从任务描述中提取）
 */
export async function precipitateFromTaskCompletion(params: {
  userId: string;
  taskId: string;
  taskTitle: string;
  taskDescription?: string | null;
  completionReflection?: string;
}) {
  const { userId, taskId, taskTitle, taskDescription, completionReflection } = params;

  // 构建沉淀内容
  const content = [
    `任务：${taskTitle}`,
    taskDescription ? `\n描述：${taskDescription}` : "",
    completionReflection ? `\n完成反思：${completionReflection}` : "",
  ].filter(Boolean).join("\n");

  if (!completionReflection && !taskDescription) {
    // 只有标题，无需沉淀
    return;
  }

  try {
    // 自动生成标签
    const tags = await extractTags(taskTitle, taskDescription || "");

    // 按反射质量决定分类
    const category = completionReflection ? "insight" : "archive";

    await db.insert(knowledgeEntries).values({
      userId,
      title: `任务完成：${taskTitle.slice(0, 60)}`,
      content,
      summary: completionReflection?.slice(0, 200) || taskTitle,
      category,
      sourceType: "task",
      sourceId: taskId,
      tags: JSON.stringify(tags),
      isAutoGenerated: true,
      isPinned: false,
      isArchived: false,
    });

    console.log(`知识沉淀完成: 任务 "${taskTitle}" → knowledge_entries`);
  } catch (error) {
    console.error("任务知识沉淀失败:", error);
    // 不阻塞主流程
  }
}

/**
 * 从每日复盘中沉淀知识
 *
 * 提取：
 * 1. 经验教训 → insight 分类
 * 2. 新洞察 → insight 分类
 * 3. 使用的技能 → tags
 */
export async function precipitateFromRetrospective(params: {
  userId: string;
  retrospectiveId: string;
  date: string;
  lessonLearned?: string;
  biggestWin?: string;
  newInsight?: string;
  skillUsed?: string[];
}) {
  const { userId, retrospectiveId, date, lessonLearned, biggestWin, newInsight, skillUsed } = params;

  const extracts: { title: string; content: string }[] = [];

  if (lessonLearned) {
    extracts.push({
      title: `复盘经验 (${date})`,
      content: `日期：${date}\n经验教训：${lessonLearned}`,
    });
  }

  if (biggestWin) {
    extracts.push({
      title: `复盘成就 (${date})`,
      content: `日期：${date}\n最大成就：${biggestWin}`,
    });
  }

  if (newInsight) {
    extracts.push({
      title: `复盘洞察 (${date})`,
      content: `日期：${date}\n新洞察：${newInsight}`,
    });
  }

  for (const extract of extracts) {
    try {
      await db.insert(knowledgeEntries).values({
        userId,
        title: extract.title,
        content: extract.content,
        summary: extract.content.slice(0, 200),
        category: "insight",
        sourceType: "retrospective",
        sourceId: retrospectiveId,
        tags: JSON.stringify(skillUsed || []),
        isAutoGenerated: true,
        isPinned: false,
        isArchived: false,
      });
    } catch (error) {
      console.error(`复盘知识沉淀失败 [${extract.title}]:`, error);
    }
  }

  if (extracts.length > 0) {
    console.log(`复盘知识沉淀完成: ${date} → ${extracts.length} 条知识`);
  }
}

/**
 * 批量回填任务和复盘已沉淀记录的嵌入向量
 */
export async function backfillKnowledgeEmbeddings(userId: string) {
  const missing = await countMissingEmbeddings(userId);
  if (missing > 0) {
    console.log(`发现 ${missing} 条缺少嵌入向量的知识条目，开始回填...`);
    const successCount = await backfillMissingEmbeddings(userId);
    console.log(`回填完成: 成功 ${successCount} 条`);
  }
}

/**
 * 用 AI 自动从任务标题和描述中提取标签
 */
async function extractTags(title: string, description: string): Promise<string[]> {
  try {
    const prompt = `从以下任务信息中，提取 3-5 个关键技能/领域标签（用逗号分隔，只输出标签，不要其他文字）：

任务标题：${title}
任务描述：${description}

示例输出格式：编程, 系统设计, 性能优化, Go语言`;

    const response = await callDeepSeek(prompt, {
      temperature: 0.3,
      maxTokens: 100,
    });

    return response.trim().split(/[,，]/).map((t: string) => t.trim()).filter(Boolean).slice(0, 5);
  } catch {
    // AI 不可用时返回空
    return [];
  }
}
