/**
 * 飞书文档链接保存到知识库 API
 *
 * POST /api/feishu/link
 * Body: { url: string, title?: string, category?: string, tags?: string[] }
 *
 * 将外部飞书文档链接保存为知识库条目并关联记录。
 */

import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth';
import { db } from '@/db';
import { feishuFiles, feishuSyncLog } from '@/db/schema/feishu';
import { knowledgeEntries } from '@/db/schema/knowledge';
import { extractTokenFromUrl } from '@/lib/feishu';
import { eq, and } from 'drizzle-orm';

export async function POST(req: NextRequest) {
  try {
    const session = await requireAuth();
    const body = await req.json();
    const { url, title, category, tags } = body;

    if (!url) {
      return NextResponse.json({ error: '缺少飞书文档链接 url' }, { status: 400 });
    }

    // 检查是否为飞书链接
    const tokenInfo = extractTokenFromUrl(url);
    if (!tokenInfo) {
      return NextResponse.json(
        { error: '无效的飞书文档链接，请提供 docx/sheets/base/wiki 格式的链接' },
        { status: 400 }
      );
    }

    const fileType =
      tokenInfo.type === 'base' ? 'bitable' : tokenInfo.type === 'unknown' ? 'doc' : tokenInfo.type;

    const fileName = title || `飞书${fileType === 'doc' ? '文档' : fileType === 'sheet' ? '表格' : '多维表格'} - ${new Date().toLocaleDateString('zh-CN')}`;

    // 检查是否已存在
    const existing = await db
      .select()
      .from(feishuFiles)
      .where(
        and(
          eq(feishuFiles.userId, session.userId),
          eq(feishuFiles.feishuUrl, url),
          eq(feishuFiles.isArchived, false)
        )
      )
      .limit(1);

    if (existing.length > 0) {
      return NextResponse.json(
        { error: '该飞书文档链接已保存', fileId: existing[0].id },
        { status: 409 }
      );
    }

    // 创建知识库条目
    const [knowledge] = await db
      .insert(knowledgeEntries)
      .values({
        userId: session.userId,
        title: fileName,
        content: `飞书文档链接: ${url}`,
        category: category || 'reference',
        sourceType: 'feishu',
        sourceId: tokenInfo.token,
        sourceName: fileName,
        tags: tags ? tags.join(',') : null,
        isAutoGenerated: true,
      })
      .returning();

    // 创建飞书文件记录
    const [fileRecord] = await db
      .insert(feishuFiles)
      .values({
        userId: session.userId,
        fileName,
        fileType,
        feishuUrl: url,
        feishuToken: tokenInfo.token,
        sourceType: 'linked',
        knowledgeEntryId: knowledge.id,
        metadata: { tags, category },
      })
      .returning();

    // 记录日志
    await db.insert(feishuSyncLog).values({
      userId: session.userId,
      configId: fileRecord.id,
      syncType: 'save_link',
      status: 'success',
      syncedAt: new Date(),
    });

    return NextResponse.json(
      {
        success: true,
        fileId: fileRecord.id,
        knowledgeId: knowledge.id,
        fileName,
        url,
      },
      { status: 201 }
    );
  } catch (error) {
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: '未登录' }, { status: 401 });
    }
    console.error('保存飞书链接失败:', error);
    return NextResponse.json(
      { error: `保存链接失败: ${error instanceof Error ? error.message : '未知错误'}` },
      { status: 500 }
    );
  }
}

/** GET: 获取已保存的飞书链接列表 */
export async function GET(req: NextRequest) {
  try {
    const session = await requireAuth();

    const rows = await db
      .select()
      .from(feishuFiles)
      .where(
        and(
          eq(feishuFiles.userId, session.userId),
          eq(feishuFiles.sourceType, 'linked'),
          eq(feishuFiles.isArchived, false)
        )
      )
      .orderBy(feishuFiles.createdAt);

    return NextResponse.json(rows);
  } catch (error) {
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: '未登录' }, { status: 401 });
    }
    console.error('获取飞书链接列表失败:', error);
    return NextResponse.json({ error: '获取链接列表失败' }, { status: 500 });
  }
}
